### ISSUE TITLE
window is not defined error occurs in the Grid when used with NextJS

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1178]
window is not defined error occurs in the Grid when used with NextJS.

![image](https://user-images.githubusercontent.com/11087921/149071575-1d7142a9-e113-4eae-b74b-42ea4d5e9a59.png)

**Comment by fableson** [comment]
When you address this issue please check other components which may have the same concerns.

NextJS loads all elements on the server side to check for SSR, so any window reference is going to fall over.

thank you!

**Comment by fableson** [comment]
As I am eager to get this operational -- do you have a sense when this dependency on the window check was added? i.e. is there an older version of the grid I could install in the interim, while awaiting this fix? thanks!

**Comment by simonssspirit** [comment]
I believe this was added in version 4.13.0 with the new draggable logic. Please try version 4.12.0 or 4.11.0.

**Comment by kspeyanski** [comment]
The issue has been fixed in the latest `dev` version of the `@progress/kendo-react-common` package (dependency of the grid).

Please refer to the changelog for the full list of changes: 
https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#d6fd56fc-f1bd-592a-ac8f-fcd60196014f

**Comment by fableson** [comment]
Thank you for the update. You mention that this is updated in the dev version -- does that mean it is not yet released?
I installed the 5.0.1 version of grid and common, etc. The problem persists

    var supportPointerEvent = Boolean(window && (typeof window !== 'undefined') && window.PointerEvent);

**Comment by kspeyanski** [comment]
Hello @fableson - The fix is released, but under the `dev` tag. This means we will release it under the `latest` tag soon, probably under version `5.0.2`. For more information about how to obtain a `dev` build, please refer to the [Obtaining Development Builds](https://www.telerik.com/kendo-react-ui/components/installation/development-builds/) article.

**Comment by fableson** [comment]
Great, thank you!

I removed my node_modules folder, modified my package.json to use all of the @dev version but still have the same error. I am sure I am doing something wrong here but not sure what.

{
  "private": true,
  "scripts": {
    "dev": "next dev -p 3001",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@progress/kendo-data-query": "dev",
    "@progress/kendo-licensing": "^1.2.1",
    "@progress/kendo-react-common": "dev",
    "@progress/kendo-react-dateinputs": "dev",
    "@progress/kendo-react-gauges": "dev",
    "@progress/kendo-react-grid": "dev",
    "@progress/kendo-react-inputs": "dev",
    "@progress/kendo-react-intl": "dev",
    "@progress/kendo-react-layout": "dev",
    "@progress/kendo-theme-default": "dev",
    "autoprefixer": "^10.0.4",
    "axios": "^0.24.0",
    "clsx": "^1.1.1",
    "ioredis": "^4.23.0",
    "mssql": "^7.3.0",
    "next": "^11.1.3",
    "postcss": "^8.1.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hot-toast": "^1.0.2",
    "swr": "^1.2.0",
    "tailwindcss": "^2.0.2",
    "tedious": "^14.0.0",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@tailwindcss/jit": "0.1.1",
    "eslint-plugin-react-hooks": "^4.3.0"
  }
}

**Comment by simonssspirit** [comment]
The same error still occurs when the Grid is selectable:

````
selectable={{
  enabled: true, <--- this line
  drag: false,
  cell: false,
  mode: 'single'
}}````
