### ISSUE TITLE
Fix error Failed to execute 'getComputedStyle' in the Grid when in a Shadow DOM

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#1238]
Fix error Failed to execute 'getComputedStyle' in the Grid when in a Shadow DOM.

`Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

This occurs since version 4.13.0, it was working on version 4.12.0:

https://codesandbox.io/s/zealous-elgamal-tri5f3

**Comment by nstoychev** [comment]
Fixed in Grid's dependency package. To get the fix, please reinstall the node modules.

**Comment by AndresAsteDeluxe** [comment]
Hi @nstoychev , I've reinstalled the node modules on https://codesandbox.io/s/zealous-elgamal-tri5f3, but the error persists. Could you please share an online example where this is working, or perhaps point me to the fixed code on node_modules's folder (so I can validate I'm using the fixed code)?
Thanks!

**Comment by nstoychev** [comment]
Hi @AndresAsteDeluxe ,

Here is a example - https://stackblitz.com/edit/react-yqmpav?file=app%2Fmain.jsx.

I am not sure why codesandbox cannot update the packages, probably because the change is in an internal package and there is some caching.

**Comment by AndresAsteDeluxe** [comment]
Thanks @nstoychev ! Clearing the cache did the trick (with an example running locally on my laptop)
