### ISSUE TITLE
Time picker animation for hours/minutes/seconds starts flickering after being changed with scroll wheel when using ReactDOM.createRoot (React 18's new rendering engine)

### ISSUE THREAD

**Issue by danieldimitrov91** [telerik/kendo-react#1303]
## I'm submitting a...
* Bug report 

## Current behavior
When scrolling into Time picker hours/minutes/seconds sections the animation starts flickering and sometimes doesn't stop.

## Expected behavior
Time picker hours/minutes/seconds animation should not flicker after scroll.

## Minimal reproduction of the problem with instructions
These are forks of the basic Time/Datetime pickers examples, just using ReactDOM.createRoot for mounting instead of ReactDOM.render. If we use ReactDOM.render even with React 18 it works as expected:

https://stackblitz.com/edit/react-ysstw2-w5uxyw?file=app%2Fmain.tsx
https://stackblitz.com/edit/react-fg5buj-n5mbbv?file=app%2Fmain.tsx

## Environment
@progress/kendo-react-dateinputs: 5.3.0
react: 18.1.0

**Comment by kdikov82** [comment]
Feedback item: [https://feedback.telerik.com/kendo-react-ui/1565638-time-picker-animation-for-hours-minutes-seconds-starts-flickering-after-being-changed-with-scroll-wheel-when-using-reactdom-createroot-react-18-s-new-rendering-engine](https://feedback.telerik.com/kendo-react-ui/1565638-time-picker-animation-for-hours-minutes-seconds-starts-flickering-after-being-changed-with-scroll-wheel-when-using-reactdom-createroot-react-18-s-new-rendering-engine)

**Comment by nstoychev** [comment]
Fixed in our development channel version.

Examples:
https://stackblitz.com/edit/react-ysstw2-mkfg2u?file=app%2Fmain.tsx
https://stackblitz.com/edit/react-fg5buj-efwumy?file=app%2Fmain.tsx

**Comment by danieldimitrov91** [comment]
> Fixed in our development channel.
> 
> Examples: https://stackblitz.com/edit/react-ysstw2-mkfg2u?file=app%2Fmain.tsx https://stackblitz.com/edit/react-fg5buj-efwumy?file=app%2Fmain.tsx

The issue still exists in both examples.
Browser: Chrome version 103.0.5060.66

**Comment by kspeyanski** [comment]
The issue has been fixed with version `v5.5.0` of the `@progress/kendo-react-dateinputs` package. Please refer to the [Changelog](https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#f41e9a37-40fc-55bf-b714-f3c8c7455a4e) for the full list of changes.
