### ISSUE TITLE
Scrolling quickly in Grid with virtual scroll in some cases results in empty Grid

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#134]
In Grid with virtual scroll, moving the mouse outside of the Grid in some cases results in empty Grid.

This is reproduced in our demo as well:

https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/#toc-virtual-scrolling

![4b21e12a-a81d-4248-8572-e6fa464543f3_ezgif-1-ed6c0e0cdaf1](https://user-images.githubusercontent.com/13251479/49223839-999d8680-f3e8-11e8-9399-86838a575b92.gif)

Multiple messages has been shown in the browser's console.
`Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See `[https://www.chromestatus.com/feature/5527160148197376](https://www.chromestatus.com/feature/5527160148197376)` for more details`

Reported in ticket: 1362834

**Comment by Xizario** [comment]
The original title represented the issue better. Happens when mouse is dragged way down after the end of the scrollbar, and the browser is moving the scroll position to the original location with wrong arguments in the event.
Does not happen on mac.

**Comment by Xizario** [comment]
Fixed in `2.5.0-dev.201812130935`

**Comment by bathach95** [comment]
I am using "@progress/kendo-react-grid": "^3.1.0" and I have the same problem when scrolling quickly:
![blank-page-3](https://user-images.githubusercontent.com/21120023/81699711-e7e5fe80-9491-11ea-922b-305db3524190.gif)
I have to reset the scrollTop to the correct value manually after scroll action is done.
Can anyone take a look?
Thank you.

**Comment by johnachris** [comment]
It still happened on @progress/kendo-react-grid: ^3.1.0. Can anyone take a look ?
