### ISSUE TITLE
TreeList getSelectedState fails with enabled virtual scrolling 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-react#1535]
The aria-rowIndex and data-grid-row-index are wrongly set when you scroll the TreeList to render new view when virtual scrolling is enabled. This causes the getSelectedState to return the wrong data key value, thus creating a wrong selected state:

- https://stackblitz.com/edit/react-km5ryu-xxv1mu?file=app%2Fmain.tsx

As a temporary workaround, the data key values can be added manually to the TR element and a custom logic for the selected state can be applied: 

- https://stackblitz.com/edit/react-km5ryu-zhjb5q?file=app%2Fmain.tsx

**Comment by kdikov82** [comment]
The same issue is observed with the Grid

**Comment by filipKovachev** [comment]
Reported again in Ticket ID: 1619793

**Comment by iadnonov** [comment]
Reported again in https://github.com/telerik/kendo-react/issues/2288

**Comment by WissamProgress** [comment]
For the Grid, there is a regression between versions 7.3.0 and 7.4.0

For 7.3.0 it was working - https://stackblitz.com/edit/react-kenryc-hgt7wj?file=package.json

For 7.4.0 it stopped working - https://stackblitz.com/edit/react-kenryc-amrqfp?file=package.json

**Comment by iadnonov** [comment]
Fixed in dev version 8.1.0-develop.19.

**Comment by vveesseelliinnaa** [comment]
Reopening the issue as it is still reproducible in version 14.4.1 here. See the following setup:

https://stackblitz.com/edit/react-km5ryu-r8x7jkan?file=package.json
