### ISSUE TITLE
NumericTextBox feedback

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-react#255]
**Client feedback:** 

We are using the KendoReact NumericTextBox but the Decimal Format functionality that we require appears to only be available in the jQuery version of the component.

On the following page: https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/formats/

The default value in the Decimal box is 5.00.

If I click on the box and type a 9, the box value changes to 5.01.

It seems that the format="n2" property not only enforces 2 decimal limit, but it rounds the number based on further input. In our situation, this is not desirable.

 
The jQuery implementation of NumericTextBox performs exactly as we would like, on several fronts. On the following page the number of decimals is limited to 2 and further input is simply ignored:

https://dojo.telerik.com/EHUberAj/5

Other undesirable behaviour in the KendoReact implementation is when trying to overwrite the existing value. For example on this page again: https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/formats/

Click the Decimals box, press backspace several times to delete all characters (press backspace until the cursor is to the left of the first 0) => it would be nicer to actually delete the characters like the jQuery implementation does.

Then, start typing numbers, for example type 123.419 => the result displayed in the KendoReact box is 1,230,419.00 => the zero's are never overwritten and the decimal place is in the wrong place. Bizarre. Once again the jQuery implementation is much nicer => the result with jQuery is 123.41

 
The jQuery implementation allows for much more desirable control of the box. Could this functionality be added to the KendoReact one? Specifically, the following behaviour:

1. Restrict decimals by throwing away further key presses - do not use the further key presses to round the number up or down

2. Deleting characters in the box should be reflected in the box - do not replace characters with 0.00 (unless implemented like a true html placeholder attribute)

3. If there is a 0.00 placeholder, the placeholder should be overwritten - current behaviour is like that of an insert resulting in wrong numbers being displayed

**Comment by simonssspirit** [comment]
Adding the following case: 1410071

In the Decimal field, entering "-.56" results in "-0.650" being displayed - notice the 5 & 6 have swapped order.

Also, the following issue: https://github.com/telerik/kendo-react/issues/98

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.

**Comment by sumitkumar202** [comment]
@vladimirivanoviliev This issue still exist in the latest versions
![image](https://github.com/telerik/kendo-react/assets/130337081/88f09b25-9812-4f2c-9b27-1efab60eb258)
