### ISSUE TITLE
Customize the layout of Grid Filter

### ISSUE THREAD

**Issue by ZiedHf** [telerik/kendo-react#28]
It would be great if we add an option to customize the Grid filter more.
For the moment the filter look like this : 
![image](https://user-images.githubusercontent.com/7974028/40537522-0fbf00ee-6007-11e8-95db-55d8a6505b66.png)

It would be very helpful if we can change the layout of filtering for example this way : 
![image](https://user-images.githubusercontent.com/7974028/40540176-1d301242-600f-11e8-89b6-92e665f5bf10.png)

**Comment by ZiedHf** [comment]
It seems like we miss the rowDoubleClick also.

**Comment by IreneMarquet** [comment]
I think is very important the idea suggested by @ZiedHf . Currently I'm working in two web applications, and the client for both have requested my team this feature as they miss this layout for the filtering. Is there any date where we can apply this type of filtering layout? @Xizario

**Comment by Xizario** [comment]
@IreneMarquet , We are expecting the filter menu to be available in the middle of September, and probably earlier in the publicly available [development builds](https://www.telerik.com/kendo-react-ui-develop/components/installation/development-builds/).

**Comment by IreneMarquet** [comment]
Hey @Xizario is the filter menu already available in the last release Kendo did? Thanks a lot.

**Comment by vladimirivanoviliev** [comment]
@IreneMarquet, currently the column menu with filters is in active development and release is expected in the following weeks. I will follow up here when we have exact date.

**Comment by lekhasy** [comment]
I want this feature so bad. :heart: :heart: :heart:
The current filter take a lot of space.

**Comment by Xizario** [comment]
@IreneMarquet
We will try to publish it into the [dev channel](https://www.telerik.com/kendo-react-ui-develop/components/grid/) later today or by Monday.

I will be glad to any feedback you have next week so we can do final touches before it gets into the official `v2.2.0` package

**Comment by lekhasy** [comment]
@Xizario 
In order to use `"@progress/kendo-react-grid": "2.2.0-dev.201810091021"`, 
I have to install `"@progress/kendo-theme-default": "2.58.0-dev.1756cf4b"` to have default theme, but it doesn't work with `"@progress/kendo-grid-react-wrapper": "2018.1.131"`.
We're using both `kendo-grid-react-wrapper` and `kendo-react-grid` in our project.
The problem is the column menu on `kendo-grid-react-wrapper` is disappear.

**Comment by lekhasy** [comment]
@Xizario I also saw that we don't have any compatibility with previous version of `@progress/kendo-react-grid`.
This is filter value generated from of kendo filter version `1.x.x`:
`{"logic":"and","filters":[{"field":"Name","operator":"contains","value":"AB"}]}`
And this is from `@progress/kendo-react-grid": "2.2.0-dev.201810091021`:
`{"logic":"and","filters":[{"logic":"and","filters":[{"field":"Name","operator":"contains","value":"AB"}]}]}`
I know that kendo now support second filter, that's reason for the different. But our API only support 1 filter.
Can you expose an option to keep old filter object format if `hideSecondFilter  = {true}`?
I think this make sense to me:
`hideSecondFilter ={ {usePriorFilterObject = {true}}}`
I know that we can easily archive that by write some extra code, but i think it's nice if kendo provide this out of the box, because thousands of project have to write this same code, and maybe have to fix their API side.

**Comment by IreneMarquet** [comment]
Hello @Xizario do you know if the development team will address before the release the issues that @lekhasy brought? or what would be your suggestions to address those?

- incompatibility of progress/kendo-theme-default": "2.58.0-dev.1756cf4b" with "@progress/kendo-grid-react-wrapper
- Be able to chose the old filter object format where only one filter was supported? , as our api is developed to use this one?

Thanks a lot in advance.

**Comment by IreneMarquet** [comment]
@Xizario we have tested the new Released version and our team found this issues:

1. Be able to chose the old filter object format where only one filter was supported: We did a fix in our code so OK
2. incompatibility of progress/kendo-theme-default": We've been able to use the old kendo-theme-defaul so OK
3. Do we have the possibility to customize the text in the filter?
We want: "Show items with value that:"
<img width="204" alt="captura de pantalla 2018-10-30 a las 12 53 15" src="https://user-images.githubusercontent.com/12745033/47716390-d556fc00-dc42-11e8-8c37-f096f4186476.png">
and we have: "Filter"
<img width="237" alt="captura de pantalla 2018-10-30 a las 12 53 08" src="https://user-images.githubusercontent.com/12745033/47716420-f15a9d80-dc42-11e8-8b8d-5fa73abf0c23.png">

4. We don't have the possibility to show which filters have been applied in the grid, as:

<img width="74" alt="captura de pantalla 2018-10-30 a las 12 55 47" src="https://user-images.githubusercontent.com/12745033/47716507-26ff8680-dc43-11e8-9840-ef7ee23ff5ab.png">

so this makes difficult user experience, as will dont know what filters have been applied. 


5. Is there any way of customizing the values we want in the dropdown? We don't want the "Is null" comparison in the app.
<img width="236" alt="captura de pantalla 2018-10-30 a las 12 56 56" src="https://user-images.githubusercontent.com/12745033/47716562-5b734280-dc43-11e8-8142-b8876007a0df.png">

Thanks a lot in advance.

**Comment by Xizario** [comment]
1. We intentionally used CompositeFilterDescriptor for the menu and FilterDescriptor for the FilterRow to be able to distinguish them in case user wants both the row and the menu.
However I see your point, and we will look for possible solutions.

2. I am not aware what is the compatibility issue with kendo-theme-default, could you give more details about it?

3. The filter text is [localizable](https://www.telerik.com/kendo-react-ui/components/grid/globalization/) using the kendo-react-intl package, so you can load the messages as resources. It would be the best case if you want to support multiple languages.
Here is an example: https://stackblitz.com/edit/react-jqfzff?file=app%2Fmain.js

4. The `columns` have `headerClassName` property that apply class to the headers per column, it can be used for styling the buttons inside it using some CSS. Let me know if you need an example for it.

5. At this point the operators are hardcoded per the type of the columns (same as for the filter raw), but we plan to improve it further. Implementing entirely custom filter Menu/filterCell, as in our demos could be challenging, so we will try to to ease the configuration of the current built-in menu.

**Comment by IreneMarquet** [comment]
Thanks a lot for the reponse. 

- 1. OK
- For 2. It was initially when we installed @progress/kendo-react-grid": "2.2.0-dev.201810091021, and we then need to install progress/kendo-theme-default": "2.58.0-dev.1756cf4b", this last had incompatibility with  progress/kendo-grid-react-wrapper": "2018.1.131" in our app. But is fine now because we are using now with "@progress/kendo-theme-default": "2.43.2" with "@progress/kendo-react-grid": "2.3.0". And works good. 
- 3 we've been able to solve with your suggestion. Thanks.
- 4. If you could provide us with an example will be very helpful. Thanks a lot.
- 5. OK

We've seen a new issue, when using date filter, and we click the calendar icon in order to filter, the calendar shows but suddenly disappears from the screen. Is this a know issue?   

Thanks a lot.

**Comment by IreneMarquet** [comment]
@Xizario , could you provide us with an example of 4? Will be very helpful, we don't achieve to highlight the filter button that has been already applied. 
Thanks a lot in advance

**Comment by Xizario** [comment]
Lets sat we add the following css to style the icon.
```css
<style>
    th.k-header.active>div>div {
    color: #fff;
    background-color: #ff6358;
    }
</style>
```
And then we add 'active' as headerClassName, depending on if there is filter expression for this column.

```jsx
<Column {...this.columnProps('ProductName')} />
```
```jsx
  columnProps(field) {
    return {
      field: field,
      columnMenu: ColumnMenu,
       headerClassName: this.state.dataState.filter &&
       this.state.dataState.filter.filters.find(c => c.field == field) ?
       'active' : ''
    }
  }
```

Here is a working example: https://stackblitz.com/edit/header-class-name?file=app/main.js
It would depend on the structure of your descriptors, as far as I see you are already modifying them. It is simplified version, but you may extend it further. It would depend of if you want to change the state of the icon only if there is something into the menu, or if there is filter in the menu or in the filter row.  Further more the same can be used for sorting for example.

We don't have an estimation for customizing the filter options. I will log a separate issue for this.

**Comment by IreneMarquet** [comment]
Hello @Xizario thanks a lot for your support, most of our issues have been solved thanks for your support, so know we have the highlight of filters, in new version datepicker is not vaninishing and there is already opened an issue for the customization of the filter options.

We have found however another issue in the date filter, when we filter by a date, it will substract one day to the filter option. So If I select: 10/30/2018, it will send to our api the value: 10/29/2018 when we select the is equal option. 

Do you know if this is handled?

Thanks a lot in advance.

**Comment by Xizario** [comment]
@IreneMarquet , could you open new issue with the date filter value problem, with a bit more explanation when it happens. The filter returns `Date` object, meaning it is not a simple `string`.
An example of how you process it and send it to your API would be great to determinate what is the problem.

**Comment by IreneMarquet** [comment]
@Xizario the date filter it was an issue from our side. We needed to convert the time taking into account timezones. Now is working in ou end. Thanks a lot. We don't have issues open, just will be missing these two enhancements, although we have been able to implement a workaround from our code, but will be missing them, as we don't see our workaround as a long term solution:

 1. "We intentionally used CompositeFilterDescriptor for the menu and FilterDescriptor for the FilterRow to be able to distinguish them in case user wants both the row and the menu.
However I see your point, and we will look for possible solutions." : We implemented a solution for this in our code but will like to have a solution in Kendo side, were we can customize it and be compatible with previous format.

5. The customization of filter options, and you opened already a card for it. 

Thanks a lot for your support because we've been able to implement the new kedo grid filter. Although we will like if those two come as anahancements. 

Thanks.

**Comment by Xizario** [comment]
Hi, we will export the GridColumnMenuFilterUI and the GridColumnMenuFilterCell classes that are now internal. And it will give the ability to wrap them and change the properties including the filter operators.

You may expect this in some of the next dev builds in a few days, and I will put an example here.

**Comment by Xizario** [comment]
@vladimirivanoviliev

**Comment by k3flo** [comment]
Any progress here?
We really need

> 5. At this point the operators are hardcoded per the type of the columns (same as for the filter raw), but we plan to improve it further. Implementing entirely custom filter Menu/filterCell, as in our demos could be challenging, so we will try to to ease the configuration of the current built-in menu.

**Comment by Xizario** [comment]
@k3flo, please see https://github.com/telerik/kendo-react/issues/123, since this part is already resolved.

**Comment by k3flo** [comment]
@Xizario 
As we do not want to use the column menu for filtering, this part is not resolved yet. We want to use the filter row and want to disable several of the default filters.

![image](https://user-images.githubusercontent.com/12381373/56341293-dbbb3f00-61b4-11e9-9a51-94009ff6672f.png)

**Comment by vladimirivanoviliev** [comment]
There is official demo:

https://www.telerik.com/kendo-react-ui/components/grid/filtering/#toc-custom-filter-operators

**Comment by Tommuh** [comment]
Is it possible to change the "Clear" and "Filter" buttons? 
I want to render my own buttons with icons. I couldn't find anything about it or do I need to make a completely new filter? (preferable don't want to do that)

For some reason the checkbox filter and the normal filter have different way of button presentation.

![image](https://user-images.githubusercontent.com/2089879/151680483-f635e8ce-335a-40b3-9323-ec928ba5e356.png)

![image](https://user-images.githubusercontent.com/2089879/151680498-3eb4f581-0696-4b79-9e6e-a09f62928acd.png)
