### ISSUE TITLE
[Bug][ColorPicker] Custom Palette colors are not applied

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#2994]
### Description

Customizing the colors of the ColorPicker palette does not work as of version 9.4.0.

### Steps To Reproduce

1. Go to https://www.telerik.com/kendo-react-ui/components/inputs/colorpicker/custom
2. Observe that the custom colors passed to the palette are not applied

### Actual Behavior

![Image](https://github.com/user-attachments/assets/c17a1e8a-10f4-4cda-9bda-cf4873601103)

### Expected Behavior

Like in this sample running with 9.3.0:
https://stackblitz.com/edit/react-jjckywsv?file=package.json

![Image](https://github.com/user-attachments/assets/d240da7a-f4d7-4aa0-98b2-38b4ecb69cb9)

### Browser

Chrome

### Browser version

latest

### OS type

MacOS

### Last working version of the KendoReact package (if regression).

9.3.1

**Comment by PaskalevStoyan** [comment]
a fix is available in `v10.1.0-develop.10`

**Comment by vveesseelliinnaa** [comment]
@PaskalevStoyan 

I am reopening the issue as it seems that the issue is still reproducible if more than one view is defined - https://stackblitz.com/edit/react-bcpwyz8p-6lwqwxxt?file=app%2Fapp.tsx

Reported in Ticket ID: 1681713

**Comment by PaskalevStoyan** [comment]
A fix is available in `10.2.0-develop.4` which covers all scenarios of the `views` prop regarding the custom palette.
