### ISSUE TITLE
[Bug][Popup] The popup is sporadically rendered with offset from its target

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-react#3385]
### Description

The popup is sporadically rendered with offset from its target. The issue can b reproduced easier on Windows, but also occurs on Mac (both Chrome and Mozilla)

### Plan

KendoReact Free

### Steps To Reproduce

1. Go to [https://stackblitz.com/edit/react-fauhnhye-4yq8hwpd?file=app%2Fapp.tsx](https://stackblitz.com/edit/react-fauhnhye-4yq8hwpd?file=app%2Fapp.tsx)
2. Click the bottom most item (the popup should be rendered above the target)
3. Observe there is offset between the button and the popup
4. Scroll down the page a bit and repeat 1-3 as needed to reproduce the issue (easier reproducible on Windows)

### Screenshots or video

[https://somup.com/cTQUIMPOFN](https://somup.com/cTQUIMPOFN)

### Actual Behavior

The popup is not rendered just above the button

### Expected Behavior

The popup must be rendered just above the button

### Browser

Chrome, Firefox

### Browser version

latest

### OS type

MacOS, Windows

### OS version

*No response*

### Last working version of the KendoReact package (if regression).

*No response*

**Comment by Sasho32** [comment]
The fix is available in v14.4.1-develop.12.

**Comment by vveesseelliinnaa** [comment]
Still reproducible in v 14.4.1 - https://stackblitz.com/edit/react-fauhnhye-skutnylw?file=package.json,index.html

Reported in Ticket ID: 1714180

**Comment by Sasho32** [comment]
The fix is available in v15.0.1-develop.1
