### ISSUE TITLE
bugs(scheduler): various improvements needed

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-react#379]
The following bugs were reported by a client:

Issue 1: November 3, 2019 Repeated on Week/Month Views:
Visit https://www.telerik.com/kendo-react-ui/components/scheduler/views/month/ or https://www.telerik.com/kendo-react-ui/components/scheduler/views/week/, navigate to the first full week in November 2019. You will notice that 11/3 is repeated for Sunday/Monday. I'm wondering if this issue is related to daylight savings time. The calendar does not have a timezone configured (just uses the default UTC and my local timezone is PST).

Issue 2: Clicking an empty all day slot does nothing:
The onSlotClick callback should be fired when clicking on an all day event. I currently have to add an event listener using document.querySelectorAll("[data-slot-allday='true']"); to get the right behavior (definitely not ideal).

Issue 3: onItemDoubleClick and onSlotDoubleClick do not work on mobile devices:
My current solution to get everything to work on desktop and mobile is to use the onItemClick and onSlotClick and to not integrate useCallback with double clicking.

Apart from fixing the explained bugs, we should take into consideration how the developer should handle events like `onSlotClick` in comparison to `onSlotDoubleClick` and provide quick and easy way to trigger a specific action, e.g `dataChange`.

I'll be updating this issues with propositions or `@dev` releases which includes any of this functionalities/fixed.

**Comment by kspeyanski** [comment]
All of the mentioned issues have been addressed with the latest `dev` version of the `@progress/kendo-react-scheduler-package`.

For the full list of changes, please refer to the Changelog:
https://www.telerik.com/kendo-react-ui-develop/components/changelogs/ui-for-react/#toc-3130-dev202004031241

**Comment by omermo** [comment]
Scheduler still doesn't work well for me on mobile, with double clicking an event doing nothing, on Kendo React v4.7.0
