### ISSUE TITLE
NumericTextBox percentage format have two issues.

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-react#5]
In this demo: https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/formats/
* Deleting the percentage sign results in 100%.
* The user is not able to delete the first digit

**Comment by Xizario** [comment]
* Typing `5` after selection all the text, including the percentage sign, results in `500%` rather than `5%`

**Comment by mwolfhoffman** [comment]
@Xizario I had the same issue with kendo-angular. Kendo isn't documenting this but the following SO solved my issue. Try it out. 
https://stackoverflow.com/questions/49908229/angular-4-kendo-numerictextbox-percentage-issue

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version `3.10.0-dev.202001150733`.

**Comment by rimmesbe** [comment]
So this still seems to be an issue when using percentage formats with decimal places:
`<NumericTextBox onChange={this.setPercentage} name='PotentialRebate' format="p1" defaultValue={0} />`

When selecting the whole value including the % it jumps to 100% when typing a number.
format="p" (works fine), format="p1" (jumps to 100%).

Looking for a workaround, thanks.

**Comment by vladimirivanoviliev** [comment]
I can confirm that this is an issue - only percent format w/o precision ('p') is handled. Currently there is no workaround, however we will try to fix it before next official release (mid May).

**Comment by Xizario** [comment]
Fixed in 3.13.0

**Comment by simonssspirit** [comment]
The issue seems to still persist on paste. If we write 1, it will make it 1.00% but if we paste 1 it will make it 100.00%.

**Comment by vladimirivanoviliev** [comment]
Fixed in latest dev version.

**Comment by vladimirivanoviliev** [comment]
Released with 3.16.0-dev.202007130614.
