### ISSUE TITLE
Grid Column Virtualization not working with multi column headers.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-react#565]
Grid Column Virtualization not working with multi-column headers:

https://stackblitz.com/edit/react-f4omwm?file=app/main.jsx

**Comment by ariefabubakar** [comment]
Hi, is this bug has been fixed?

**Comment by simonssspirit** [comment]
@ariefabubakar The issue still occurs.

I will raise its priority.

**Comment by ariefabubakar** [comment]
> @ariefabubakar The issue still occurs.
> 
> I will raise its priority.

Glad to hear that. Any temporary solution for this bug?

**Comment by InaGlushkova** [comment]
Requested again in 1497530

**Comment by Xizario** [comment]
https://stackblitz.com/edit/react-fcdkju?file=app/main.jsx
Reported again by @Stamo-Gochev
