### ISSUE TITLE
Cannot resize Grid column in webpack dev environment

### ISSUE THREAD

**Issue by jason-xiao-st** [telerik/kendo-react#75]
Here is the stacktrace.

`Uncaught TypeError: Cannot set property 'width' of undefined
    at ColumnResize.../../node_modules/@progress/kendo-react-grid/dist/es/drag/ColumnResize.js.ColumnResize.updateColElements (ColumnResize.js:97)
    at ColumnResize.../../node_modules/@progress/kendo-react-grid/dist/es/drag/ColumnResize.js.ColumnResize.setWidths (ColumnResize.js:85)
    at ColumnResize.../../node_modules/@progress/kendo-react-grid/dist/es/drag/ColumnResize.js.ColumnResize.dragHandler (ColumnResize.js:30)
    at Object.resize (HeaderRow.js:59)
    at release (ColumnResizer.js:29)
    at Draggable._releaseHandler (main.js:1)
    at HTMLSpanElement.Draggable._pointerup (main.js:136)`

Working in prod mode.

versions:
`"webpack": "4.4.1"`
` "@progress/kendo-data-query": "1.4.1",`
`  "@progress/kendo-drawing": "1.5.7",`
` "@progress/kendo-react-grid": "1.2.0",`
`  "@progress/kendo-react-inputs": "1.2.0",`
`  "@progress/kendo-react-intl": "1.2.0",`
`  "@progress/kendo-react-pdf": "1.2.0"`

**Comment by vladimirivanoviliev** [comment]
I tried to reproduce the issue on our side but without success. Could you please prepare small example project where the issue is reproduced and provide download link here? Thank you in advance.

**Comment by sumanla13a** [comment]
Also having the same issue. It is because of `React.StrictMode` that calls the render method twice.

You can reproduce it [here](https://github.com/sumanla13a/kendo-react-strict-issue)

**Comment by vladimirivanoviliev** [comment]
@sumanla13a The issue is fixed on our side - you can test it in the latest version (2.1) and let us know of the result.

**Comment by sumanTitan** [comment]
@vladimirivanoviliev I tried installing v2.1
I cannot resize the grid-column size there as well.

**Comment by sumanla13a** [comment]
@vladimirivanoviliev 
I just installed the v2.1 and it doesn't seem to help. The column resize still throws the same error.

**Comment by sumanla13a** [comment]
Was this fixed? I installed the latest version 2.3.0 and it still throws the same error.

**Comment by Xizario** [comment]
Should work in 2.8.0

**Comment by xarety** [comment]
Still not working in the last version, but now w/o errors in the console.
